name: AurumPVP
main: io.github.jesp1999.aurumpvp.AurumPVP
version: 0.1.2.4
api-version: 1.16

author: Dhumina, Julian, Ian
commands:
  kit:
    description: Gives player a kit
    usage: /kit [player] <kit name>
    permission: aurumpvp.kit
    permission-message: You don't have aurumpvp.kit
  countdown:
    description: This is a demo command.
    usage: /countdown <numberOfSeconds>
    permission: aurumpvp.countdown
    permission-message: You don't have aurumpvp.countdown
  reloadkits:
    description: Reloads kits.
    usage: /reloadkits
    permission: aurumpvp.reload
    permission-message: You can't reload!
  rk:
    description: Reloads kits.
    usage: /rk
    permission: aurumpvp.reload
    permission-message: You can't reload!