name: AurumPVP
main: io.github.jesp1999.aurumpvp.AurumPVP
version: 0.3.1.0
api-version: 1.16

author: Dhumina, Julian, Ian
commands:
  aurumpvp:
    description: Lists information about the AurumPVP plugin
    usage: /aurumpvp
    permission: aurumpvp.info
    permission-message: You don't have the permission aurumpvp.info
  countdown:
    description: This is a demo command.
    usage: /countdown <numberOfSeconds>
    permission: aurumpvp.countdown
    permission-message: You don't have the permission aurumpvp.countdown
  deletekit:
    description: Deletes a kit from the kits.json configuration
    usage: /deletekit <kit name>
    permission: aurumpvp.kit.delete
    permission-message: You don't have the permission aurumpvp.kit.delete
  dk:
    description: Deletes a kit from the kits.json configuration
    usage: /dk <kit name>
    permission: aurumpvp.kit.delete
    permission-message: You don't have the permission aurumpvp.kit.delete
  givekit:
    description: Gives player a kit
    usage: /givekit [player] <kit name>
    permission: aurumpvp.kit.give
    permission-message: You don't have the permission aurumpvp.kit.give
  gk:
    description: Gives player a kit
    usage: /gk [player] <kit name>
    permission: aurumpvp.kit.give
    permission-message: You don't have the permission aurumpvp.kit.give
  listkits:
    description: Lists the current kits in the kits.json configuration
    usage: /listkits
    permission: aurumpvp.kit.list
    permission-message: You don't have the permission aurumpvp.kit.list
  lk:
    description: Lists the current kits in the kits.json configuration
    usage: /lk
    permission: aurumpvp.kit.list
    permission-message: You don't have the permission aurumpvp.kit.list
  reloadkits:
    description: Reloads kits.
    usage: /reloadkits
    permission: aurumpvp.kit.reload
    permission-message: You don't have the permission aurumpvp.kit.reload
  rk:
    description: Reloads kits.
    usage: /rk
    permission: aurumpvp.kit.reload
    permission-message: You don't have the permission aurumpvp.kit.reload
  setamount:
    description: Changes the quantity of the item in the main hand.
    usage: /setamount <number>
    permission: aurumpvp.inventory.setamount
    permission-message: You don't have the permission aurumpvp.inventory.setamount
  sa:
    description: Changes the quantity of the item in the main hand.
    usage: /ss <number>
    permission: aurumpvp.inventory.setamount
    permission-message: You don't have the permission aurumpvp.inventory.setamount
  setcolor:
    description: Changes the color of the item in the main hand.
    usage: /setcolor <hex color>
    permission: aurumpvp.inventory.setcolor
    permission-message: You don't have the permission aurumpvp.inventory.setcolor
  sc:
    description: Changes the color of the item in the main hand.
    usage: /sc <hex color>
    permission: aurumpvp.inventory.setcolor
    permission-message: You don't have the permission aurumpvp.inventory.setcolor
  setlore:
    description: Changes the lore of the item in the main hand.
    usage: /setlore <lore>
    permission: aurumpvp.inventory.setlore
    permission-message: You don't have the permission aurumpvp.inventory.setlore
  sl:
    description: Changes the lore of the item in the main hand.
    usage: /sl <lore>
    permission: aurumpvp.inventory.setlore
    permission-message: You don't have the permission aurumpvp.inventory.setlore
  setname:
    description: Changes the name of the item in the main hand.
    usage: /setname <name>
    permission: aurumpvp.inventory.setname
    permission-message: You don't have the permission aurumpvp.inventory.setname
  sn:
    description: Changes the name of the item in the main hand.
    usage: /sn <name>
    permission: aurumpvp.inventory.setname
    permission-message: You don't have the permission aurumpvp.inventory.setname
  setslot:
    description: Moves the item in your hand into the specified slot
    usage: /setslot <slot name>
    permission: aurumpvp.inventory.setslot
    permission-message: You don't have the permission aurumpvp.setslot
  ss:
    description: Moves the item in your hand into the specified slot
    usage: /ss <slot name>
    permission: aurumpvp.inventory.setslot
    permission-message: You don't have the permission aurumpvp.setslot
  writekit:
    description: Writes the current player's inventory to a given kit name and category
    usage: /writekit <kit name> <kit category>
    permission: aurumpvp.kit.write
    permission-message: You don't have the permission aurumpvp.kit.write
  wk:
    description: Writes the current player's inventory to a given kit name and category
    usage: /wk <kit name> <kit category>
    permission: aurumpvp.kit.write
    permission-message: You don't have the permission aurumpvp.kit.write