package io.github.jesp1999.aurumpvp.kit;


public enum KitType {
//ranged
NINJA, BOMBER, TACTICIAN, HUNTER, SNIPER, ARCHER, ASSASSIN, SCOUT, MEDIC, MARAUDER,
//physical
KNIGHT, BERSERKER, NYMPH, CHALLENGER, MINER, REAPER,
//magic
MAGE, SHAPESHIFTER, PYROMANCER, NECROMANCER, SPIRIT, DRUID, WITCH_DOCTOR, WARPER, PHASER,
//tank
PALADIN, PROTECTOR, BLACKSMITH, MACHINIST, ANGEL, FROST_WARDEN
}
